# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"
#ZSH_THEME="gnzh"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git osx svn)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
if [ -e ~/.paths ]; then
    . ~/.paths
fi
#source $HOME/bin/paths
#export PATH=$PATH:/Users/petrisi/.rvm/gems/ruby-2.0.0-p0/bin:/Users/petrisi/.rvm/gems/ruby-2.0.0-p0@global/bin:/Users/petrisi/.rvm/rubies/ruby-2.0.0-p0/bin:/Users/petrisi/.rvm/bin:/Users/petrisi/nvm/v0.8.14/bin:/Users/petrisi/Applications/apache-jmeter-2.6/bin:/Users/petrisi/Applications/sqlplus:/Users/petrisi/Dropbox/bin:/Users/petrisi/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

if [ -e ~/.alias ]; then
    . ~/.alias
fi

function svndiff {
  svn diff "$@" | colordiff | less -RFX
}

if [ -e ~/.zshrc.local ]; then
    . ~/.zshrc.local
fi
